export const holonet = [
    {
        "name": "Skavak",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "Known to some as The Jackal of the Stars, Skavak stole the Smugglers' ship in pursuit of the Fatal Fortune. A galaxy-spanning chase and several assassination attempts later, he would meet his end at the event horizon of The Long Shadow.",
        "image": "skavak.jpg"
    },
    {
        "name": "Corso Riggs",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Smuggler Party",
        "living": true,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "He is an Ord Mantell native, and a true patriot. Corso worked for Viidu before Viidu's unjust and untimely death, and is somewhere adrift in Ord Mantell even now. Sometimes he sheds a single tear thinking of the gun Skavak stole.",
        "image": "corsoriggs.jpg"
    },
    {
        "name": "Viidu",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "Connoisseur of fine art, wine, and anything luxurious, Viidu ran smuggling jobs from his gilded den on Ord Mantell. Killed in cold blood by Syreena, to gain Skavak's favor... and all for nothing, as he left the planet without her.",
        "image": "viidu.jpg"
    },
    {
        "name": "Syreena",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "Spared by the Smugglers after being caught murdering Viidu, her plan to gain Skavak's affection failed when he left Ord Mantell without her.",
        "image": "Syreena.jpg"
    },
    {
        "name": "Darmas Pollaran",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "He hangs out in the old Galactic Market, finding secrets and dispensing them... for a fee. Or, in the case of information regarding Skavak, gladly.",
        "image": "darmaspollaran.jpg"
    },
    {
        "name": "Miel Muwn",
        "tags": ["npc"],
        "species": "Sullustan",
        "affiliation": "Sullustan Constable Brigade",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "The Deputizer of Fools, Miel Muwn enlisted the Smugglers to aid him in his noble quest... that happened to align with the Smugglers' interests perfectly. Later, rescued from the Justicars and sent on his way. May he find non-fatal fortune - preferably the Murustavn Ruby.",
        "image": "mielmuwn.jpg"
    },
    {
        "name": "Kixi",
        "tags": ["npc"],
        "species": "Mirialan",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "Rescued from the Black Sun by the Smugglers, she had been enslaved and forced to slice for them, including scrubbing Skavak's criminal records. Once freed, she restored the records - with a little extra on top.",
        "image": "Kixi.jpg"
    },
    {
        "name": "Risha",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Smuggler Party",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "A princess, born of the Royal Line of Ayelcris. She is the daughter of Nok Drayen, and spared the Smugglers after they had so graciously restored her father in pursuit of his treasure. Currently aboard the Jackal.", 
        "image": "risha.jpg"
    },
    {
        "name": "Agent Soganti",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Republic Customs Enforcement",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": "A customs officer on Taris, he was suspicious, but not suspicious enough.",
        "image": "agentsoganti.jpg"
    },
    {
        "name": "Beryl Thorne",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": "The sentimental former partner of Tyrodall, she preferred selling Taris artifacts to the less profitable demographic of families affected by the bombing of Taris.",
        "image": "berylthorne.jpg"
    },
    {
        "name": "Tyrodall",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": " Beryl Thorne's former partner, he faked his own death and began smuggling artifacts in core samples to far more lucrative Republic customers. He came to an agreement with the Smugglers.",
        "image": "tyrodall.jpg"
    },
    {
        "name": "Drooga",
        "tags": ["npc"],
        "species": "Hutt",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "The hungriest boy on Nar Shaddaa. He collects endangered enemies from across the galaxy to serve as main courses on his party barge.",
        "image": "drooga.jpg"
    },
    {
        "name": "Ga'ram",
        "tags": ["npc"],
        "species": "Twi'lek",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "The chief steward of Drooga's party barge. The primary means by which the Smugglers communicated with Drooga.",
        "image": "ga'ram.jpg"
    },
    {
        "name": "Lazhae",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "A tinkerer of genes, this future conqueror of the galaxy just has to perfect his Lazhaean creations. Was, somehow, not murdered for his ethical shortcomings.",
        "image": "lazhae.jpg"
    },
    {
        "name": "Momi Andrell",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "The daughter of a senator, the Smugglers left her to be experimented upon by Lazhae. Probably alive... to some degree.",
        "image": "momiandrell.jpg"
    },
    {
        "name": "Cessec",
        "tags": ["npc"],
        "species": "Killik",
        "affiliation": "Killiks",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "A hive mind of the Kiliks, one of Cessec's components was saved on Nar Shaddaa by the Smugglers on Drooga's party barge. Later, on Alderaan, was convinced to take over House Bayliss.",
        "image": "cessec.jpg"
    },
    {
        "name": "Lenn Teraan",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Teraan",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune"],
        "bio": "One of the few surviving members of House Teraan, he enlisted the help of the Smugglers to retrieve an item from their former house, now owned by House Bayliss.",
        "image": "lennteraan.jpg"
    },
    {
        "name": "Cedonia Teraan",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Teraan",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune"],
        "bio": "One of the few surviving members of House Teraan, she enlisted the help of the Smugglers to retrieve an item from their former house, now owned by House Bayliss.",
        "image": "cedoniateraan.jpg"
    },
    {
        "name": "Peema Ahuff",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Alde",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "The curator of the Royal Museum of Alderaan, Peema cares deeply for his work. He does not suffer fools or fakes.",
        "image": "peemaahuff.jpg"
    },
    {
        "name": "Nok Drayen",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Temako",
        "campaign": ["The Fatal Fortune"],
        "bio": "From king in exile to pirate, Nok Drayen amassed a fortune and then faked his death after being incurably poisoned. Attempted to convince Risha to kill the Smugglers and assume the crown once unfrozen, years later.",
        "image": "nokdrayen.jpg"
    },
    {
        "name": "Darth Skotia",
        "tags": ["npc"],
        "species": "Human (Cyborg)",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "Mostly cyborg, an EMP rocket at the command of Darth Zash ended his life.",
        "image": "darthskotia.jpg"
    },
    {
        "name": "Darth Zash",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "Gaslighting girlboss of the Sith, she groomed Kass to be her successor. Literally.",
        "image": "darthzash.jpg"
    },
    {
        "name": "Darth Thanaton",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "Master of Darth Skotia and Darth Zash, he hated Darth Zash with a passion.",
        "image": "darththanaton.jpg"
    },
    {
        "name": "Aloysius Kallig",
        "tags": ["npc"],
        "species": "Unknown",
        "affiliation": "Ancient Sith",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "Apprentice of Tulak Hord, he forcefully inhabited Kass. A frequent visitor in flashbacks, he faded away after making peace with Kass (mostly).",
        "image": "aloysiuskallig.jpg"
    },
    {
        "name": "Major Bessiker",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "An Imperial Resource officer on Morian, Bessiker's son was captured by scavengers on his very first mission.",
        "image": "majorbessiker.jpg"
    },
    {
        "name": "Hiram Bessiker",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "Captured by scavengers on his first mission on Morian. Racist, and now freed.",
        "image": "hirambessiker.jpg"
    },
    {
        "name": "Iannos Tyrek",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire (formerly, defected)",
        "living": false,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "Scientist on Morian, executed for treason against the Empire after being captured by the Inquisitors.",
        "image": "iannostyrek.jpg"
    },
    {
        "name": "Captain Ilun",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "Second in command to Commander Bessiker.",
        "image": "captainilun.jpg"
    },
    {
        "name": "Rylee Dray",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Cult of the Screaming Blade",
        "living": true,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "Given the cult in the name of Kass, along with Destris. A pretty decent choice for the leader of a cult.",
        "image": "ryleedray.jpg"
    },
    {
        "name": "Destris Veran",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Cult of the Screaming Blade",
        "living": true,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "Given the cult in the name of Kass, along with Rylee. Probably not a great choice for the leader of a cult.",
        "image": "destrisveran.jpg"
    },
    {
        "name": "Lord Paladius",
        "tags": ["npc"],
        "species": "Sith",
        "affiliation": "Cult of the Screaming Blade",
        "living": false,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "Former leader of the Cult of the Screaming Blade, he was couped and replaced by Kass in dramatic fashion.",
        "image": "lordpaladius.jpg"
    },
    {
        "name": "Elana Thul",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Thul",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "Lady of house Thul.",
        "image": "elanathul.jpg"
    },
    {
        "name": "Urtel Moren",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "Personal bodyguard of Elana Thul. Is continuously seething.",
        "image": "urtelmoren.jpg"
    },
    {
        "name": "Rehanna Rist",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Rist",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "House Rist is a house of assassins, and Rehanna is no exception. Not considered to be the most noble of houses, but it's best not to get too far on their bad side.",
        "image": "rehannarist.jpg"
    },
    {
        "name": "Aland Organa",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Jedi Order",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "Jedi Knight of House Organa, and held the keys to their vault.",
        "image": "alandorgana.jpg"
    },
    {
        "name": "Saras",
        "tags": ["npc"],
        "species": "Killik",
        "affiliation": "Killiks",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "They love harmonica music. Bortol provided them with a concert.",
        "image": "saras.jpg"
    },
    {
        "name": "Kreeble Bob",
        "tags": ["npc"],
        "species": "Jawa",
        "affiliation": "Unknown",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "Shoots. Leaves. Refuses to elaborate.",
        "image": "kreeblebob.jpg"
    },
    {
        "name": "Overseer Harkun",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Korriban",
        "campaign": ["Legacies of the Damned"],
        "bio": "Taught Kass in the Sith Academy, and absolutely detests him. Not racist, just really hates slaves.",
        "image": "overseerharkun.jpg"
    },
    {
        "name": "Braden",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "Former bounty hunter, current corpse. Slain by Sedyn Kayn at the command of Tarro Blood in an unsuccessful attempt to stop the Bounty Hunters. Survived by Mako, KV-27, and The Wanderer.",
        "image": "braden.jpg"
    },
    {
        "name": "Jory",
        "tags": ["npc"],
        "species": "Nikto",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "Murdered along with Braden. Loved weapons.",
        "image": "jory.jpg"
    },
    {
        "name": "Varnan",
        "tags": ["npc"],
        "species": "Gran",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "Murdered along with Braden.",
        "image": "varnan.jpg"
    },
    {
        "name": "Mako",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Bounty Hunters",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A talented slicer, Mako kicks back and relaxes while the Bounty Hunters go out and nearly get killed. She worked closely with Braden and KV-27, before joining up with the Bounty Hunters. Do NOT mispronounce her name.",
        "image": "mako.jpg"
    },
    {
        "name": "Tarro Blood",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Mandalorians",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A firm believer that all warfare is based on deception, if deception means murder. He also believes that non-Mandalorians shouldn't compete in the Great Hunt, or something like that. It's hard to remember motivations through the film of Braden's blood coating the memories.",
        "image": "tarroblood.jpg"
    },
    {
        "name": "Sedyn Kyne",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Mandalorians",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A Mandalorian, he works with Tarro Blood. Murdered Braden and his team.",
        "image": "sedynkyne.jpg"
    },
    {
        "name": "Suudaa Nem'ro",
        "tags": ["npc"],
        "species": "Hutt",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "All bounty hunters in the Great Hunt require a sponsor, and he rather reluctantly chose the Bounty Hunters after trying to kill and mislead them multiple times. Likelihood of backstabbing them again: 95%.",
        "image": "suudaanem'ro.jpg"
    },
    {
        "name": "Carnus",
        "tags": ["npc"],
        "species": "Houk",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "The lieutenant of Nemro, he appreciates a good solid dose of violence.",
        "image": "carnus.jpg"
    },
    {
        "name": "Doctor Albea",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Republic",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A bounty target, she was inexplicably saved by the Bounty Hunters and let go.",
        "image": "doctoralbea.jpg"
    },
    {
        "name": "C1-AW",
        "tags": ["npc"],
        "species": "Droid",
        "affiliation": "C1-AW",
        "living": true,
        "planet": "Bounty Hunters' Ship",
        "campaign": ["The Great Hunt"],
        "bio": "A synthetic demon, this ungrateful thing delights in torturing Wawa. Kill on sight. Bounty Reward: 10000 credits.",
        "image": "C1AW.png"
    },
    {
        "name": "Crysta Markon",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "Handler of the Bounty Hunters, she assigns them their targets. Immune to the Wanderer's rizz.",
        "image": "crystamarkon.jpg"
    },
    {
        "name": "The Huntmaster",
        "tags": ["npc"],
        "species": "Wookiee",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "A rare albino Wookiee, he runs the hunt!",
        "image": "thehuntmaster.jpg"
    },
    {
        "name": "Assistant Huntmaster Lek",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "The assistant... to the Huntmaster.",
        "image": "assistanthuntmasterlek.jpg"
    },
    {
        "name": "Lieutenant Major Pirrell",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "The most loyal servant of the Empire. Unjustly prosecuted by Admiral Ivernus for 'crimes against the Empire'.",
        "image": "lieutenantmajorpirrell.jpg"
    },
    {
        "name": "Murghir",
        "tags": ["npc"],
        "species": "Cathar",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "An undercover operative for the rival team in the Great Hunt on Balmorra. Probably had sex with Major Pirrell.",
        "image": "murghir.jpg"
    },
    {
        "name": "Zalia",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "Slicer sent in to help take over a droid factory. Killed by the Wanderer for no reason after the mission was completed.",
        "image": "zalia.jpg"
    },
    {
        "name": "Admiral Ivernus",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "'Silence, you pathetic excuse for an officer. I have come all the way here just to see you executed in person.' - Admiral Ivernus",
        "image": "admiralivernus.jpg"
    },
    {
        "name": "Gele'ren",
        "tags": ["npc"],
        "species": "Twi'lek",
        "affiliation": "Hutt Cartel",
        "living": false,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "A lieutenant for the Hutt Cartel. Killed by the Eidolon's true damage droids.",
        "image": "gele'ren.jpg"
    },
    {
        "name": "Anuli",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Hutt Cartel",
        "living": false,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "Sacrificial boy. Dared to talk about his future and doomed to die.",
        "image": "anuli.jpg"
    },
    {
        "name": "The Eidolon",
        "tags": ["npc"],
        "species": "Zabrak",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "The leading figure of Eidolon Securities. Captured and delivered to a Hutt's garden, he is now the favorite nesting spot for giant carnivorous bats.",
        "image": "theeidolon.jpg"
    },
    {
        "name": "Nar Shaddaa",
        "tags": ["planet"],
        "region": "Hutt Space",
        "affiliation": "Hutt Cartel",
        "campaign": ["The Great Hunt", "The Fatal Fortune"],
        "bio": "The city-moon of Nal Hutta. May the desperate prosper.",
        "image": "nar shaddaa loading.jpg"
    },
    {
        "name": "Coruscant",
        "tags": ["planet"],
        "region": "The Core Worlds",
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Urban sprawl made manifest, this ecumenopolis is the keystone of the Republic. Tourists are advised to avoid the lowest levels of the city.",
        "image": "coruscant_loading.jpg"
    },
    {
        "name": "Alderaan",
        "tags": ["planet"],
        "region": "The Core Worlds",
        "affiliation": "Independent",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "The houses of Alderaan lay split along factional lines, plunging the planet into an endless civil war. More important, however, are the Kiliks swarming from beneath the crust to retake the surface and drive out the alien invaders.",
        "image": "alderaan_loading.jpg"
    },
    {
        "name": "Nal Hutta",
        "tags": ["planet"],
        "region": "Hutt Space",
        "affiliation": "Hutt Cartel",
        "campaign": ["The Great Hunt"],
        "bio": "The homeworld of the Hutts. Connoisseurs of swamps and toxic fumes will love it here - the planet has several award winning swamps from Galactic Weekly's Top 10 Swamps To Be Buried Alive In.",
        "image": "hutta loading.jpg"
    },
    {
        "name": "Balmorra",
        "tags": ["planet"],
        "region": "The Core Worlds",
        "affiliation": "Empire",
        "campaign": ["The Great Hunt"],
        "bio": "A rocky industrial world. Surrendered to the Empire in the Treaty of Coruscant.",
        "image": "balmorra loading.jpg"
    },
    {
        "name": "Dromund Kaas",
        "tags": ["planet"],
        "region": "Seat of the Empire",
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "The dark capital planet of the Sith Empire. Extremely stormy. Bring an umbrella.",
        "image": "dromund kaas loading.jpg"
    },
    {
        "name": "Dxun",
        "tags": ["planet"],
        "region": "The Mid-Rim",
        "affiliation": "Mandalorians",
        "campaign": ["The Great Hunt"],
        "bio": "This moon shares an atmosphere with its planetary brother Onderon. Certain flying creatures even migrate between the two.",
        "image": "dxun loading.jpg"
    },
    {
        "name": "Korriban",
        "tags": ["planet"],
        "region": "Seat of the Empire",
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "The ancient homeworld of the Sith. Home to the least stable teenagers in the galaxy.",
        "image": "korriban loading.jpg"
    },
    {
        "name": "Morian",
        "tags": ["planet"],
        "region": "Outer Rim Territories",
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "Toxic wastelands, mutant wildlife, and deranged scavengers. What's not to love?",
        "image": "morian loading.jpg"
    },
    {
        "name": "Ord Mantell",
        "tags": ["planet"],
        "region": "The Mid-Rim",
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Locked in a war against Separatists, who have a cool volcano base.",
        "image": "ord mantell loading.jpg"
    },
    {
        "name": "Taris",
        "tags": ["planet"],
        "region": "Seat of the Empire",
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Bombed out during the Jedi Civil War several hundred years ago, it is now a mire of swamp and ruin.",
        "image": "taris loading.jpg"
    },
    {
        "name": "Temako",
        "tags": ["planet"],
        "region": "Outer Rim Territories",
        "affiliation": "Independent",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "Skyscrapers strain for the stars while trash piles around their foundations. Capitalism, baby.",
        "image": "temako loading.jpg"
    },
    {
        "name": "Tython",
        "tags": ["planet"],
        "region": "The Core Worlds",
        "affiliation": "Republic",
        "campaign": ["Suivvi's Betrayal"],
        "bio": "The original home of the Jedi, rediscovered after the end of the war. Many have retreated there as public opinion of the Jedi sours.",
        "image": "tython loading.jpg"
    },
    {
        "name": "The Architects",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Galaxy",
        "description": "Although the Republic has existed for millennia, there is evidence to suggest that long before its founding, a highly advanced race ruled the galaxy. Referred to as the 'Architects' by scholars, these beings possessed remarkable technology capable of constructing or realigning solar systems. The Corellia system, for example, appears to have been artificially constructed. These claims would seem extraordinary, but many of the Architects' machines survived the ages. The Vultar system was home to an immense 'Cosmic Turbine' that could only have been Architect technology, before misuse destroyed both the turbine and the Vultar system itself. The fabled Centerpoint Station is thought to be an Architect installation, though many species have claimed it as the work of their own people. In addition to their engineering marvels, it is believed that the Architects seeded the Core Worlds with life--particularly humans--though some attribute this to the Rakata's Infinite Empire. Despite the proof of their achievements, however, there is little evidence to suggest where the Architects came from or what eventually became of them.",
        "image": ""
    },
    {
        "name": "Ancient Civilizations",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Galaxy",
        "description": "In the period after the mysterious Architects vanished from the galaxy millennia ago, several great civilizations rose in their place. The intellectual Columi species created a vast but peaceful empire, focusing on academic pursuits while droids and elaborate machines labored for them. As a result, the Columi evolved enormous craniums and tiny bodies. The strange, reptilian Kwa, who achieved interstellar travel through Infinity Gates that allowed them to effectively teleport between worlds, rose and mysteriously fell, eventually devolving into simple lizards. The cephalopod Gree also reached their apex in this time, creating technological marvels that have rarely been equaled. Eventually, on the backs of these civilizations would come the Rakata and their Infinite Empire.",
        "image": ""
    },
    {
        "name": "The Zhell-Taung War",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "Coruscant",
        "description": "In the millennia before the founding of the Republic, humans had not yet developed spaceflight. One human population--perhaps the only one--was confined to Coruscant, divided into thirteen tribes. This nearly proved disastrous when a volcanic eruption caused a near-extinction event, wiping out a large percentage of human life. This made the humans easy prey for the Taung, a gray-skinned species that reveled in battle. Awed by the majesty of the eruption's ash cloud, the Taung took the name 'Warriors of the Shadow,' descended on the surviving humans and subjugated them. Gradually the fighting force of the thirteen human tribes--known as the Battalions of Zhell--mustered a resistance against the Taung. After years of struggle, the Battalions managed to repel the Taung and claim their freedom. Coruscant has been the seat of humanity ever since.",
        "image": ""
    },
    {
        "name": "Birth of the Jeda'ii",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "Tython",
        "description": "",
        "image": ""
    },
    {
        "name": "The Ascension of King Adas",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "Korriban",
        "description": "The ancient Sith on Korriban--not an order of Force users, but a distinct species native to the planet--were distinctive for their yellow eyes and blood-red skin. But the warrior Adas was unlike his brothers; his skin was jet-black and he towered over his fellow Sith. Through violence and cunning, he fought his way to become ruler of the Sith and united their nations through a bloody war. He later took the title 'Sith'ari,' meaning 'overlord.' King Adas's ascension may have been helped by an untrained Force sensitivity. Certainly Adas was long-lived; his reign lasted three hundred years, and only came to an end when the Infinite Empire launched an assault on Korriban. The title Sith'ari remains a key tenet of Sith lore, eventually coming to refer to a perfect being in Sith philosophy.",
        "image": ""
    },
    {
        "name": "Conquest of the Infinite Empire",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Galaxy",
        "description": "The 'Infinite Empire' was the name the Rakata people gave to their magnificent but ultimately flawed civilization--one that eventually encompassed more than five hundred known worlds. Their rise was fueled by their impressive technology, powered by what would later be called the Force. Using it, the Rakata developed the first known hyperdrives. Slowly, the Rakata became corrupted by their power. They began enslaving entire species, including the peoples of Coruscant. The Rakata also attacked Korriban, ruled by the great King Adas. Although their attack failed to enslave the pureblooded Sith species, King Adas was killed. Without his leadership, Korriban was plunged into civil war. The Rakata's slaves were put to work building monuments to the Infinite Empire's glory. Among the Infinite Empire's achievements was the Star Forge, a space station capable of producing nigh-endless droids and starships. However, the Star Forge was fueled by the dark side of the Force. Using it only hastened the Rakata's fall.",
        "image": ""
    },
    {
        "name": "The Force War",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "Tython",
        "description": "",
        "image": ""
    },
    {
        "name": "Fall of the Rakata",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Galaxy",
        "description": "The Rakata species had created a glorious Infinite Empire with their Force-fueled machines, but cracks were beginning to show. The cruelty of the Rakata to their slaves and occupied worlds grew more pronounced. If a planet's population rebelled, that entire world would be burned to glass. Despite this, more slave rebellions began to rise across the galaxy, forcing the Rakata to divide their forces to deal with them. A plague, perhaps created by the rebelling slaves or by Rakata dissidents, began to decimate the Rakata population. The Rakata realized that, possibly due to the plague, they were losing their connection to the Force; without it, they were cut off from their technology. The fall of the Infinite Empire, once it began, was swift. The slaves overwhelmed their Rakata overseers, who fled into the Unknown Regions of the galaxy. The Rakata degenerated into a tribal culture and even resorted to cannibalism. The Infinite Empire was gone; only its technology was left behind.",
        "image": ""
    },
    {
        "name": "Rise of Interstellar Spaceflight",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Core Worlds, Seat of the Empire",
        "description": "Free of the Infinite Empire's enslavement, the humans of Coruscant began investigating the technology their Rakata masters had left. Although they couldn't use the Force-powered machines, the humans learned enough to make tentative forays into space, using slower-than-light vessels manned by crews kept in suspended animation for decades at a time. Slowly, humans began to colonize new worlds: Alsakan, Metellos, Alderaan. The first explorers to Alderaan discovered the remains of strange insect nests, later known to be built by the Killiks. The pureblooded Sith species on Korriban, having survived both the Infinite Empire's onslaught and a bloody civil war after the death of their king, also became intrigued by the machines the Rakata left behind. Suddenly a spacefaring civilization, the Sith species left Korriban and eventually established a new colony on the planet Ziost.",
        "image": ""
    },
    {
        "name": "Invention of the Hyperspace Cannon",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Galaxy",
        "description": "Early spaceflights were conducted with sleeper ships, their crews preserved via suspended animation over the long journeys to other worlds. But these journeys were incredibly slow. Remembering the efficient hyperdrive technology of the Infinite Empire, the most brilliant scientists of the galaxy began to study what remained of those machines, despite the claims of Tiran, the Drall scientist who centuries before said that nothing could travel faster than the speed of light. Eventually, this led to the development of a hyperspace 'cannon.' These cannons allowed a ship to be propelled into hyperspace, though a second cannon was required for a ship to return to its origin point. The Core Worlds quickly established a hyperspace cannon network. The children of Coruscant soon encountered the Duros civilization, whose people became some of the earliest--and most daring--hyperspace explorers. The true colonization of the galaxy had begun.",
        "image": ""
    },
    {
        "name": "The Ascension of Xim the Despot",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "Tion Cluster",
        "description": "As the Core Worlds began to expand, another power in the galaxy was rising. The Tion Cluster, an area of the Mid-Rim inhabited by the descendants of ancient sleeper ship crews, had developed a new hyperspace beacon technology based on fragments left by the Infinite Empire--far superior than the hyperspace cannons previously in use. The Tion Cluster was gradually conquered by an arrogant and powerful pirate prince, known to history as the despot Xim. Using the new hyperspace technology, he despoiled world after world, taking slaves and ruthlessly expanding his territory. His rule of the Tion Cluster lasted for thirty years and saw the conquest of hundreds of thousands of planets. Xim might have continued his rule unchallenged even longer, but he chose to expand his empire into a new area of space, one already inhabited by the powerful Hutt Empire.",
        "image": ""
    },
    {
        "name": "The Tionese-Hutt War",
        "tags": ["history"],
        "year": "",
        "era": "Pre-Republic",
        "location": "The Mid-Rim, Hutt Space",
        "description": "Seeking to expand his territory, the ancient Tionese despot Xim began exploring the Si'klaata Cluster--and for the first time, encountered a force that could challenge him. This region belonged to the Hutt Empire. Although young, the Hutt Empire had already grown immensely powerful through its criminal enterprises, helped by the long lifespan of the Hutts. The Hutts correctly assessed the threat Xim presented and poured resources into fighting him near the planet Vontor. Despite their strength, the Hutts were not certain of victory until they discovered the Si'klaata Cluster was home to several other powerful species, including the Nikto, Klatooinians, and Weequay. In a typical gambit, the Hutts managed to persuade these three species to sign the Treaty of Vontor, which bound them to the Hutts in perpetual slavery. With these additional forces, the Hutts overwhelmed Xim at the third Battle of Vontor. Xim died a Hutt prisoner, leaving his vast holdings and territory free for the taking.",
        "image": ""
    },
]

export const template = [
    {
        "name": "",
        "tags": ["npc"],
        "species": "",
        "affiliation": "",
        "living": true,
        "planet": "",
        "campaign": [""],
        "bio": "",
        "image": ""
    },
    {
        "name": "",
        "tags": ["planet"],
        "region": "",
        "affiliation": "",
        "campaign": [""],
        "bio": "",
    }, 
    {
        "name": "",
        "tags": ["history"],
        "year": "",
        "era": "",
        "location": "",
        "description": "",
        "image": ""
    },
]
