export const holonet = [
    {
        "name": "Skavak",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "skavak.jpg"
    },
    {
        "name": "Corso Riggs",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Smuggler Party",
        "living": true,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "corsoriggs.jpg"
    },
    {
        "name": "Viidu",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "viidu.jpg"
    },
    {
        "name": "Syreena",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Ord Mantell",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "Syreena.jpg"
    },
    {
        "name": "Darmas Pollaran",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "darmaspollaran.jpg"
    },
    {
        "name": "Miel Muwn",
        "tags": ["npc"],
        "species": "Sullustan",
        "affiliation": "Sullustan Constable Brigade",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "mielmuwn.jpg"
    },
    {
        "name": "Kixi",
        "tags": ["npc"],
        "species": "Mirialan",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "Kixi.jpg"
    },
    {
        "name": "Risha",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Smuggler Party",
        "living": true,
        "planet": "Coruscant",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "risha.jpg"
    },
    {
        "name": "Agent Soganti",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Republic Customs Enforcement",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "agentsoganti.jpg"
    },
    {
        "name": "Beryl Thorne",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "berylthorne.jpg"
    },
    {
        "name": "Tyrodall",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Taris",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "tyrodall.jpg"
    },
    {
        "name": "Drooga",
        "tags": ["npc"],
        "species": "Hutt",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "drooga.jpg"
    },
    {
        "name": "Ga'ram",
        "tags": ["npc"],
        "species": "Twi'lek",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "ga'ram.jpg"
    },
    {
        "name": "Lazhae",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "lazhae.jpg"
    },
    {
        "name": "Momi Andrell",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "momiandrell.jpg"
    },
    {
        "name": "Cessec",
        "tags": ["npc"],
        "species": "Killik",
        "affiliation": "Killiks",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "cessec.jpg"
    },
    {
        "name": "Lenn Teraan",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Teraan",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "lennteraan.jpg"
    },
    {
        "name": "Cedonia Teraan",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Teraan",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "cedoniateraan.jpg"
    },
    {
        "name": "Peema Ahuff",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Alde",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "",
        "image": "peemaahuff.jpg"
    },
    {
        "name": "Nok Drayen",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Temako",
        "campaign": ["The Fatal Fortune"],
        "bio": "",
        "image": "nokdrayen.jpg"
    },
    {
        "name": "Darth Skotia",
        "tags": ["npc"],
        "species": "Human (Cyborg)",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "darthskotia.jpg"
    },
    {
        "name": "Darth Zash",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "darthzash.jpg"
    },
    {
        "name": "Darth Thanaton",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "darththanaton.jpg"
    },
    {
        "name": "Aloysius Kallig",
        "tags": ["npc"],
        "species": "Unknown",
        "affiliation": "Ancient Sith",
        "living": false,
        "planet": "Dromund Kaas",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "aloysiuskallig.jpg"
    },
    {
        "name": "Major Bessiker",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "majorbessiker.jpg"
    },
    {
        "name": "Hiram Bessiker",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "hirambessiker.jpg"
    },
    {
        "name": "Iannos Tyrek",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire (formerly, defected)",
        "living": false,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "iannostyrek.jpg"
    },
    {
        "name": "Captain Ilun",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Morian",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "captainilun.jpg"
    },
    {
        "name": "Rylee Dray",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Cult of the Screaming Blade",
        "living": true,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "ryleedray.jpg"
    },
    {
        "name": "Destris Veran",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Cult of the Screaming Blade",
        "living": true,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "destrisveran.jpg"
    },
    {
        "name": "Lord Paladius",
        "tags": ["npc"],
        "species": "Sith",
        "affiliation": "Cult of the Screaming Blade",
        "living": false,
        "planet": "Temako",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "lordpaladius.jpg"
    },
    {
        "name": "Elana Thul",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Thul",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "elanathul.jpg"
    },
    {
        "name": "Urtel Moren",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "urtelmoren.jpg"
    },
    {
        "name": "Rehanna Rist",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "House Rist",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "rehannarist.jpg"
    },
    {
        "name": "Aland Organa",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Jedi Order",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "alandorgana.jpg"
    },
    {
        "name": "Saras",
        "tags": ["npc"],
        "species": "Killik",
        "affiliation": "Killiks",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "saras.jpg"
    },
    {
        "name": "Kreeble Bob",
        "tags": ["npc"],
        "species": "Jawa",
        "affiliation": "Unknown",
        "living": true,
        "planet": "Alderaan",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "kreeblebob.jpg"
    },
    {
        "name": "Overseer Harkun",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Korriban",
        "campaign": ["Legacies of the Damned"],
        "bio": "",
        "image": "overseerharkun.jpg"
    },
    {
        "name": "Braden",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "braden.jpg"
    },
    {
        "name": "Jory",
        "tags": ["npc"],
        "species": "Nikto",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "jory.jpg"
    },
    {
        "name": "Varnan",
        "tags": ["npc"],
        "species": "Gran",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "varnan.jpg"
    },
    {
        "name": "Mako",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Bounty Hunters",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A talented slicer, Mako kicks back and relaxes while the Bounty Hunters go out and nearly get killed. She worked closely with Braden and KV-27, before joining up with the Bounty Hunters. Do NOT mispronounce her name.",
        "image": "mako.jpg"
    },
    {
        "name": "Tarro Blood",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Mandalorians",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "A firm believer that all warfare is based on deception, if deception means murder. He also believes that non-Mandalorians shouldn't compete in the Great Hunt, or something like that. It's hard to remember motivations through the film of Braden's blood coating the memories.",
        "image": "tarroblood.jpg"
    },
    {
        "name": "Sedyn Kyne",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Mandalorians",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "sedynkyne.jpg"
    },
    {
        "name": "Suudaa Nem'ro",
        "tags": ["npc"],
        "species": "Hutt",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "All bounty hunters in the Great Hunt require a sponsor, and he rather reluctantly chose the Bounty Hunters after trying to kill and mislead them multiple times. Likelihood of backstabbing them again: 95%.",
        "image": "suudaanem'ro.jpg"
    },
    {
        "name": "Carnus",
        "tags": ["npc"],
        "species": "Houk",
        "affiliation": "Hutt Cartel",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "carnus.jpg"
    },
    {
        "name": "Doctor Albea",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Republic",
        "living": true,
        "planet": "Nal Hutta",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "doctoralbea.jpg"
    },
    {
        "name": "C1-AW",
        "tags": ["npc"],
        "species": "Droid",
        "affiliation": "C1-AW",
        "living": true,
        "planet": "Bounty Hunters' Ship",
        "campaign": ["The Great Hunt"],
        "bio": "A synthetic demon, this ungrateful thing delights in torturing Wawa. Kill on sight. Bounty Reward: 10000 credits.",
        "image": "C1AW.png"
    },
    {
        "name": "Crysta Markon",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "crystamarkon.jpg"
    },
    {
        "name": "The Huntmaster",
        "tags": ["npc"],
        "species": "Wookiee",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "thehuntmaster.jpg"
    },
    {
        "name": "Assistant Huntmaster Lek",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "The Great Hunt",
        "living": true,
        "planet": "Dxun",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "assistanthuntmasterlek.jpg"
    },
    {
        "name": "Lieutenant Major Pirrell",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": true,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "lieutenantmajorpirrell.jpg"
    },
    {
        "name": "Murghir",
        "tags": ["npc"],
        "species": "Cathar",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "murghir.jpg"
    },
    {
        "name": "Zalia",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Unaffiliated",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "zalia.jpg"
    },
    {
        "name": "Admiral Ivernus",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Sith Empire",
        "living": false,
        "planet": "Balmorra",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "admiralivernus.jpg"
    },
    {
        "name": "Gele'ren",
        "tags": ["npc"],
        "species": "Twi'lek",
        "affiliation": "Hutt Cartel",
        "living": false,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "A lieutenant for the Hutt Cartel. Killed by the Eidolon's true damage droids.",
        "image": "gele'ren.jpg"
    },
    {
        "name": "Anuli",
        "tags": ["npc"],
        "species": "Human",
        "affiliation": "Hutt Cartel",
        "living": false,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "anuli.jpg"
    },
    {
        "name": "The Eidolon",
        "tags": ["npc"],
        "species": "Zabrak",
        "affiliation": "Unaffiliated",
        "living": true,
        "planet": "Nar Shaddaa",
        "campaign": ["The Great Hunt"],
        "bio": "",
        "image": "theeidolon.jpg"
    },
    {
        "name": "Nar Shaddaa",
        "tags": ["planet"],
        "affiliation": "Hutt Cartel",
        "campaign": ["The Great Hunt", "The Fatal Fortune"],
        "bio": "The city-moon of Nal Hutta. May the desperate prosper.",
        "image": "nar shaddaa loading.jpg"
    },
    {
        "name": "Coruscant",
        "tags": ["planet"],
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Urban sprawl made manifest, this ecumenopolis is the keystone of the Republic. Tourists are advised to avoid the lowest levels of the city.",
        "image": "coruscant_loading.jpg"
    },
    {
        "name": "Alderaan",
        "tags": ["planet"],
        "affiliation": "Independent",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "The houses of Alderaan lay split along factional lines, plunging the planet into an endless civil war. More important, however, are the Kiliks swarming from beneath the crust to retake the surface and drive out the alien invaders.",
        "image": "alderaan_loading.jpg"
    },
    {
        "name": "Nal Hutta",
        "tags": ["planet"],
        "affiliation": "Hutt Cartel",
        "campaign": ["The Great Hunt"],
        "bio": "The homeworld of the Hutts. Connoisseurs of swamps and toxic fumes will love it here - the planet has several award winning swamps from Galactic Weekly's Top 10 Swamps To Be Buried Alive In.",
        "image": "hutta loading.jpg"
    },
    {
        "name": "Balmorra",
        "tags": ["planet"],
        "affiliation": "Empire",
        "campaign": ["The Great Hunt"],
        "bio": "A rocky industrial world. Surrendered to the Empire in the Treaty of Coruscant.",
        "image": "balmorra loading.jpg"
    },
    {
        "name": "Dromund Kaas",
        "tags": ["planet"],
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "The dark capital planet of the Sith Empire. Extremely stormy. Bring an umbrella.",
        "image": "dromund kaas loading.jpg"
    },
    {
        "name": "Dxun",
        "tags": ["planet"],
        "affiliation": "Mandalorians",
        "campaign": ["The Great Hunt"],
        "bio": "This moon shares an atmosphere with its planetary brother Onderon. Certain flying creatures even migrate between the two.",
        "image": "dxun loading.jpg"
    },
    {
        "name": "Korriban",
        "tags": ["planet"],
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "The ancient homeworld of the Sith. Home to the least stable teenagers in the galaxy.",
        "image": "korriban loading.jpg"
    },
    {
        "name": "Morian",
        "tags": ["planet"],
        "affiliation": "Empire",
        "campaign": ["Legacies of the Damned"],
        "bio": "Toxic wastelands, mutant wildlife, and deranged scavengers. What's not to love?",
        "image": "morian loading.jpg"
    },
    {
        "name": "Ord Mantell",
        "tags": ["planet"],
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Locked in a war against Separatists, who have a cool volcano base.",
        "image": "ord mantell loading.jpg"
    },
    {
        "name": "Taris",
        "tags": ["planet"],
        "affiliation": "Republic",
        "campaign": ["The Fatal Fortune"],
        "bio": "Bombed out during the Jedi Civil War several hundred years ago, it is now a mire of swamp and ruin.",
        "image": "taris loading.jpg"
    },
    {
        "name": "Temako",
        "tags": ["planet"],
        "affiliation": "Independent",
        "campaign": ["The Fatal Fortune", "Legacies of the Damned"],
        "bio": "Skyscrapers strain for the stars while trash piles around their foundations. Capitalism, baby.",
        "image": "temako loading.jpg"
    },
    {
        "name": "Tython",
        "tags": ["planet"],
        "affiliation": "Republic",
        "campaign": ["Suivvi's Betrayal"],
        "bio": "The original home of the Jedi, rediscovered after the end of the war. Many have retreated there as public opinion of the Jedi sours.",
        "image": "tython loading.jpg"
    },
]

export const template = [
    {
        "name": "",
        "tags": ["npc"],
        "species": "",
        "affiliation": "",
        "living": true,
        "planet": "",
        "campaign": [""],
        "bio": "",
    },
    {
        "name": "",
        "tags": ["planet"],
        "affiliation": "",
        "campaign": [""],
        "bio": "",
    },
]
