export const conditions = [
    {
        "name": "Bleeding X",
        "effects": ["A Bleeding creature takes X True Damage at the start of each of their turns. This True Damage ignores Temporary HP.",
                    "Bleeding does not stack. If a creature is inflicted with more than one Bleeding effect, they are only affected by the highest level effect.",
                    "Bleeding is removed by healing, using an action within 5ft of the creature to attempt a DC10 Medicine Check, or being reduced to 0HP."],
    },
    {
        "name": "Blinded",
        "effects": ["A Blinded creature can’t see and automatically fails any Ability Check that requires sight.",
                    "Unless a Blinded creature benefits from powers or a special sense, ranged attacks and spells have a range of 10ft and Attack Rolls suffer Disadvantage.",
                    "Attack Rolls against Blinded creatures have Advantage."],
    },
    {
        "name": "Charmed",
        "effects": ["A charmed creature can’t attack the charmer or target the charmer with harmful abilities or enhanced effects.",
                    "The charmer has Advantage on any ability check to interact socially with the creature.",
                ],
    },
    {
        "name": "Corroded",
        "effects": ["A Corroded creature has their AC reduced by the amount of Corroded stacks they have. Their AC cannot be reduced below 10 + their Dexterity Modifier by this effect.",
                    "At the end of a Corroded creature's turn, their Corroded stacks are halved. If they only had 1 stack, it is removed."
                ],
    },
    {
        "name": "Dazed",
        "effects": ["A Dazed creature has Disadvantage on Wisdom Saves, cannot take reactions, and cannot add their Dexterity modifier to their AC.",
                ],
    },
    {
        "name": "Deafened",
        "effects": ["A Deafened creature can’t hear and automatically fails any Check that requires hearing.",
                    ],
    },
    {
        "name": "Diseased",
        "effects": ["A Diseased creature suffers effects that vary based on the disease.",
                    ],
    },
    {
        "name": "Enfeebled",
        "effects": ["A Enfeebled creature has disadvantage on Physical Saves.",
                    ],
    },
    {
        "name": "Exhausted",
        "effects": ["This condition is cumulative. Each time you receive it, you gain 1 level of Exhaustion. You die if your exhaustion level exceeds 10. ",
                    "When you make an Attack, Save, or Check, you subtract your Exhaustion level from the roll.",
                    "Subtract your Exhaustion level from the Save DC of any power you cast or ability you use.",
                    "Finishing a Long Rest removes 1 of your levels of Exhaustion.",
                    ],
    },
    {
        "name": "Frightened",
        "effects": ["A Frightened creature has Disadvantage on Attacks and Checks while the source of its fear is within line of sight.",
        "The creature can’t willingly move closer to the source of its fear.",
                    ],
    },
    {
        "name": "Grappled",
        "effects": ["A Grappled creature has its speed reduced to 0.",
                    "The condition ends if the grappler is Incapacitated.",
                    "The condition also ends if an effect removes the Grappled creature from the reach of the grappler or grappling effect.",
                    ],
    },
    {
        "name": "Ignited",
        "effects": ["An Ignited creature suffers Fire Damage at the end of each of its turns. A damage value in parentheses appears with this condition—the Fire Damage the creature takes at the end of its turn.",
                    "If the target or a creature within 5 feet of it uses an action to put out the flames, or if some other effect douses the flames, the creature is no longer Ignited.",
                    ],
    },
    {
        "name": "Incapacitated",
        "effects": ["An Incapacitated creature can’t take actions or reactions.",
                    "An Incapacitated creature automatically fails Strength, Dexterity, and Constitution Checks.",
                    ],
    },
    {
        "name": "Invisible",
        "effects": ["An invisible creature is considered unseen to other creatures, without the aid of powers or a special sense that allow it to detect the creature, as described in “Unseen Attackers and Targets” in Chapter 9. For the purpose of hiding, the creature is heavily obscured. The creature’s location can be detected by any noise it makes or any tracks it leaves.",
                    "Unless a creature benefits from powers or a special sense that allow it to detect the creature, attack rolls against the creature have disadvantage, and the creature’s attack rolls have advantage.",
                    ],
    },
    {
        "name": "Paralyzed",
        "effects": ["A paralyzed creature is incapacitated (see the condition) and can’t move or speak.",
                    "The creature automatically fails Strength and Dexterity saving throws, as if it had rolled a 1 on the save. Attack rolls against the creature have advantage.",
                    "Any attack that hits the creature is a critical hit if the attacker is within 5 feet of the creature.",
                    ],
    },
    {
        "name": "Petrified",
        "effects": ["A petrified creature is transformed, along with any object it is wearing or carrying, into a solid inanimate substance (usually stone). Its weight increases by a factor of ten, and it ceases aging.",
                    "The creature is incapacitated (see the condition), can’t move or speak, and is unaware of its surroundings.",
                    "Attack rolls against the creature have advantage.",
                    "The creature automatically fails Strength and Dexterity saving throws, as if it had rolled a 1 on the save.",
                    "The creature has resistance to all damage.",
                    "The creature is immune to poison and disease, although a poison or disease already in its system is suspended, not neutralized.",
                    ],
    },
    {
        "name": "Poisoned",
        "effects": ["A poisoned creature has disadvantage on attack rolls and ability checks.",
                    ],
    },
    {
        "name": "Potent",
        "effects": ["When a Potent creature forces enemies to roll a Save, they have disadvantage on that Save.",
                    ],
    },
    {
        "name": "Prone",
        "effects": ["A prone creature’s only movement option is to crawl, unless it stands up and thereby ends the condition.",
                    "The creature has disadvantage on melee attack rolls.",
                    "The creature has disadvantage on ranged attack rolls against targets within 30 feet.",
                    "An attack roll against the creature has advantage if the attacker is within 5 feet of the creature. Otherwise, the attack roll has disadvantage.",
                    ],
    },
    {
        "name": "Rallied",
        "effects": ["A Rallied creature can take one additional action on top of their regular action during their turn. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action.",
                    "At the end of this creature's turn, they are no longer Rallied.",
                    ],
    },
    {
        "name": "Restrained",
        "effects": ["A restrained creature has 4 slowed levels.",
                    "Attack rolls against the creature have advantage, and the creature’s attack rolls have disadvantage.",
                    "The creature has disadvantage on Dexterity saving throws.",
                    ],
    },
    {
        "name": "Shocked",
        "effects": ["A shocked creature can’t take reactions.",
                    "On its turn, a shocked creature can take either an action or a bonus action, but not both.",
                    ],
    },
    {
        "name": "Slowed",
        "effects": ["Some abilities, effects, and hazards can lead to a special condition called slowed. Slowed is measured in four levels. An effect can give a creature one or more levels of slowed, as specified in the effect’s description.",
                    "TABLE[[LEVEL, EFFECT],[1, Speed reduced by 15 feet],[2, Speed reduced by 25 feet],[3, Speed reduced by 30 feet],[4, Speed reduced to 0 and can't benefit from any bonus to speed]]",
                    "If an already slowed creature suffers another effect that causes it to be slowed, its current slowed level increases by the amount specified in the effect’s description.",
                    "An effect that removes slowed reduces its level as specified in the effect’s description, with all slowed effects ending if a creature’s slowed level is reduced below 1.",
                    ],
    },
    {
        "name": "Steadfast",
        "effects": ["A Steadfast creature has advantage on Physical Saves.",
                    ],
    },
    {
        "name": "Stunned",
        "effects": ["A Stunned creature is Incapacitated (see the condition), can’t move, and can speak only falteringly.",
                    ],
    },
    {
        "name": "Tenacious",
        "effects": ["A Tenacious creature has advantage on Mental Saves.",
                    ],
    },
    {
        "name": "Unconscious",
        "effects": ["An unconscious creature is Incapacitated (see the condition), can’t move or speak, and is unaware of its surroundings.",
                    "The creature drops whatever it’s holding and falls prone.",
                    "The creature automatically fails Strength and Dexterity Saves, as if it had rolled a 1.",
                    "Attack Rolls against the creature have Advantage.",
                    "Any attack that hits the creature is a Critical Hit if the attacker is within 5 feet of the creature.",
                    ],
    },
    {
        "name": "Unstoppable",
        "effects": ["An Unstoppable creature reduces the next instance of damage they receive to 1. One stack is consumed when taking damage and at the end of their turn. ",
                    "Unstoppable creatures cannot be moved or have their movement prevented by any external forces. ",
                    ],
    },
    {
        "name": "Weakened",
        "effects": ["A creature suffering from a stack of Weakened has their attack rolls and saving throws reduced by 1. This effect can stack up to 10 times. At the end of a creature's turn, their stacks decay by half. If they only have one stack, it is removed.",
                    "A creature suffering from any number of Weakened stacks heals at a slower rate. When an effect restores hit points to the creature, the amount of hit points restored is halved.",
                    ],
    },
    {
        "name": "Weak-Willed",
        "effects": ["A Weak-Willed creature has disadvantage on Mental Saves.",
                    ],
    },
]